### ISSUE TITLE
there is too many duplicated code betwen api-particulier & api-particulier-auth

### ISSUE THREAD

**Issue by rdubigny** [betagouv/api-particulier-auth#32]
For instance, /api-particulier-auth/api/lib seems to be a pure copy of /api-particulier/api/lib

Do you have ideas about a way to factorise this ? Is this code still needed in api-particulier ?

**Comment by pknoth** [comment]
lib is part of how we design the express application. I think it is not bad to share high level design between the two apps

**Comment by rdubigny** [comment]
we should at least use a submodule to factorize lib folder
